# Generated by Django 3.1.4 on 2020-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201217_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FB', 'Football'), ('RD', 'Rides'), ('TE', 'Tech')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
